language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy
  - source activate test-environment
  - pip install .

# command to run tests
script:
  - python setup.py test
